// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrkSMwrPO6Denv_oMoBQIUIEqG5KbZeII',
    appId: '1:701848881897:web:f2f9b4b52db732d6ba7e78',
    messagingSenderId: '701848881897',
    projectId: 'relieflink-2ad5d',
    authDomain: 'relieflink-2ad5d.firebaseapp.com',
    storageBucket: 'relieflink-2ad5d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtlaX1UkZqD6TsD--n0FMl-ZC2youz2n4',
    appId: '1:701848881897:android:e9d3a3e72c361e67ba7e78',
    messagingSenderId: '701848881897',
    projectId: 'relieflink-2ad5d',
    storageBucket: 'relieflink-2ad5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR-vDZmrvHQkUf1OsqRA339FsJZxM5Dpc',
    appId: '1:701848881897:ios:cdc2ea494f1a4094ba7e78',
    messagingSenderId: '701848881897',
    projectId: 'relieflink-2ad5d',
    storageBucket: 'relieflink-2ad5d.firebasestorage.app',
    iosBundleId: 'com.example.reliefLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR-vDZmrvHQkUf1OsqRA339FsJZxM5Dpc',
    appId: '1:701848881897:ios:cdc2ea494f1a4094ba7e78',
    messagingSenderId: '701848881897',
    projectId: 'relieflink-2ad5d',
    storageBucket: 'relieflink-2ad5d.firebasestorage.app',
    iosBundleId: 'com.example.reliefLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrkSMwrPO6Denv_oMoBQIUIEqG5KbZeII',
    appId: '1:701848881897:web:c4e27d3c5447c53aba7e78',
    messagingSenderId: '701848881897',
    projectId: 'relieflink-2ad5d',
    authDomain: 'relieflink-2ad5d.firebaseapp.com',
    storageBucket: 'relieflink-2ad5d.firebasestorage.app',
  );
}
